dataset:
  original_path: data/2/original_data.csv
  masked_path: data/2/config50_masked.csv
  target_variable: is_booking
  model_script: data/2/model4.py
masking:
  attributes:
    serial:
    - function: generalize
      params:
        M: 2
    date_time:
    - function: suppress
      params: {}
    site_name:
    - function: generalize
      params:
        M: 5
    posa_continent:
    - function: suppress
      params: {}
    user_location_country:
    - function: generalize
      params:
        M: 4
    user_location_region:
    - function: erase_digits
      params:
        num_digits: 1
    user_location_city:
    - function: erase_digits
      params:
        num_digits: 3
    orig_destination_distance:
    - function: suppress
      params: {}
    user_id:
    - function: suppress
      params: {}
    is_mobile:
    - function: erase_digits
      params:
        num_digits: 1
    is_package:
    - function: erase_digits
      params:
        num_digits: 3
    channel:
    - function: erase_digits
      params:
        num_digits: 3
    srch_ci:
    - function: erase_digits
      params:
        num_digits: 2
    srch_co:
    - function: suppress
      params: {}
    srch_adults_cnt:
    - function: generalize
      params:
        M: 4
    srch_children_cnt:
    - function: suppress
      params: {}
    srch_rm_cnt:
    - function: erase_digits
      params:
        num_digits: 1
    srch_destination_id:
    - function: erase_digits
      params:
        num_digits: 2
    srch_destination_type_id:
    - function: generalize
      params:
        M: 3
    cnt:
    - function: generalize
      params:
        M: 3
    hotel_continent:
    - function: erase_digits
      params:
        num_digits: 2
    hotel_country:
    - function: generalize
      params:
        M: 2
    hotel_market:
    - function: generalize
      params:
        M: 2
    hotel_cluster:
    - function: generalize
      params:
        M: 3
reconstruction:
  ipf_params:
    max_iter: 1000
    tol: 1.0e-06
  algorithm: sampling
  output_path: results/2/config50_reconstruction.tsv
