dataset:
  original_path: data/1/original_data.csv
  masked_path: data/1/config17_masked.csv
  target_variable: Air Quality
  model_script: data/1/model4.py
masking:
  attributes:
    Temperature:
    - function: suppress
      params: {}
    Humidity:
    - function: suppress
      params: {}
    PM2.5:
    - function: suppress
      params: {}
    PM10:
    - function: suppress
      params: {}
    NO2:
    - function: erase_digits
      params:
        num_digits: 2
    SO2:
    - function: generalize
      params:
        M: 2
    CO:
    - function: generalize
      params:
        M: 3
    Proximity_to_Industrial_Areas:
    - function: generalize
      params:
        M: 3
    Population_Density:
    - function: suppress
      params: {}
reconstruction:
  ipf_params:
    max_iter: 1000
    tol: 1.0e-06
  algorithm: sampling
  output_path: results/1/config17_reconstruction.tsv
