dataset:
  original_path: data/3/original_data.csv
  masked_path: data/3/config19_masked.csv
  target_variable: income
  model_script: data/3/model4.py
masking:
  attributes:
    age:
    - function: erase_digits
      params:
        num_digits: 2
    workclass:
    - function: erase_digits
      params:
        num_digits: 1
    fnlwgt:
    - function: generalize
      params:
        M: 2
    education:
    - function: generalize
      params:
        M: 5
    education_num:
    - function: generalize
      params:
        M: 4
    marital_status:
    - function: generalize
      params:
        M: 5
    occupation:
    - function: generalize
      params:
        M: 3
    relationship:
    - function: erase_digits
      params:
        num_digits: 2
    race:
    - function: suppress
      params: {}
    sex:
    - function: erase_digits
      params:
        num_digits: 2
    capital_gain:
    - function: erase_digits
      params:
        num_digits: 1
    capital_loss:
    - function: generalize
      params:
        M: 3
    hours_per_week:
    - function: generalize
      params:
        M: 4
    native_country:
    - function: suppress
      params: {}
reconstruction:
  ipf_params:
    max_iter: 1000
    tol: 1.0e-06
  algorithm: sampling
  output_path: results/3/config19_reconstruction.tsv
