dataset:
  original_path: data/3/original_data.csv
  masked_path: data/3/config05_masked.csv
  target_variable: income
  model_script: data/3/model4.py
masking:
  attributes:
    age:
    - function: generalize
      params:
        M: 2
    workclass:
    - function: erase_digits
      params:
        num_digits: 3
    fnlwgt:
    - function: erase_digits
      params:
        num_digits: 2
    education:
    - function: suppress
      params: {}
    education_num:
    - function: suppress
      params: {}
    marital_status:
    - function: erase_digits
      params:
        num_digits: 2
    occupation:
    - function: suppress
      params: {}
    relationship:
    - function: erase_digits
      params:
        num_digits: 1
    race:
    - function: erase_digits
      params:
        num_digits: 2
    sex:
    - function: erase_digits
      params:
        num_digits: 1
    capital_gain:
    - function: erase_digits
      params:
        num_digits: 3
    capital_loss:
    - function: generalize
      params:
        M: 4
    hours_per_week:
    - function: generalize
      params:
        M: 5
    native_country:
    - function: suppress
      params: {}
reconstruction:
  ipf_params:
    max_iter: 1000
    tol: 1.0e-06
  algorithm: sampling
  output_path: results/3/config05_reconstruction.tsv
